// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzntrxtlmnhiewqaftcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16bnRyeHRsbW5oaWV3cWFmdGNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzMwODYsImV4cCI6MjA2NTcwOTA4Nn0.IXDbrY4i0iFyvI5cQaCjku6AC3GiUTQUgOdIgyWHG6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);